# Generated by Django 4.0.1 on 2022-01-09 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cousse',
            new_name='Course',
        ),
    ]
